apiVersion: v1
kind: Service                
metadata:
  name: product-go-micro-service  
spec:
  type: NodePort  # When Node receives a request, 
  ports:                       
  - name: http
    port: 9090  # Our service will run on http Port 9090
    targetPort: 9090  # Our application to exposed to this port 9090
  selector:
    app: product-go-micro