apiVersion: v1
kind: Service                
metadata:
  name: product-go-micro-service  
spec:
  type: NodePort                
  ports:                       
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: product-go-micro